#!/usr/bin/env sh

#          ┌────────┐
# ┌──────┐ │        │
# │LVDS1*│ │  HDM1  │
# └──────┘ └────────┘
"$(dirname -- $(realpath -- $0))/xrandr" \
  --output LVDS1 --mode 1600x900  --pos 0x180  --rotate normal --primary \
  --output HDMI1 --mode 1920x1080 --pos 1600x0 --rotate normal
